Program ::= Expr
Expr    ::= Const | Var | Mul | Diff | Add1 | Zero | If | Let | Proc | Call
Const   ::= Number
Var     ::= Id
Mul     ::= '*' '(' Expr ',' Expr ')'
Diff    ::= '-' '(' Expr ',' Expr ')'
Add1    ::= 'add1' '(' Expr ')'
Zero    ::= 'zero?' '(' Expr ')'
If      ::= 'if' Expr 'then' Expr 'else' Expr
Let     ::= 'let' Id '=' Expr 'in' Expr
Proc    ::= 'proc' '(' Id ')' Expr
Call    ::= '(' Expr Expr ')'
Number  ::= [0-9]+
Id      ::= [a-z]+

/* Use https://www.bottlecaps.de/rr/ui to view it as a Railroad Diagram. */
